apiVersion: v1
kind: Secret
metadata:
  name: grafana-permanent-token
  namespace: monitoring-stress
  annotations:
    kubernetes.io/service-account.name: "grafana-monitoring"
type: kubernetes.io/service-account-token
