{
 "title": "Etcd by Prometheus",
 "description": "Etcd Dashboard for Prometheus metrics scraper",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "ETCD - Métricas Importantes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Grafico Latencia API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb=\"POST\"}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gráfico de Latência (etcd)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Etcd - Queries acima 100ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_slow_apply_total[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round Trip - Latencia entre Masters - Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fila de Commit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_pending[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending)",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Visão Geral ETCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Etcd possui um líder?",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "max(etcd_server_has_leader)" },
      {}
     ]
    },
    {
     "title": "Consumo de Memoria - Cluster",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}} Resident Memory" }
     ]
    },
    {
     "title": "Consumo de CPU - Masters",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 15, "y": 61 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"etcd\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total[1m]))",
       "legendFormat": "The total number of bytes received by grpc clients"
      },
      {
       "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total[1m]))",
       "legendFormat": "The total number of bytes sent to grpc clients"
      }
     ]
    },
    {
     "title": "Disk Sync Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le))",
       "legendFormat": "{{instance}} WAL fsync"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (instance, le))",
       "legendFormat": "{{instance}} DB fsync"
      }
     ]
    },
    {
     "title": "Disks operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum[1m]))",
       "legendFormat": "\tThe latency distributions of fsync called by wal"
      },
      {
       "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum[1m]))",
       "legendFormat": "The latency distributions of commit called by backend"
      }
     ]
    }
   ]
  },
  {
   "title": "Visão Geral - Network ETCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Traffic In",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(etcd_network_client_grpc_received_bytes_total[5m])",
       "legendFormat": "{{instance}} Client Traffic In"
      }
     ]
    },
    {
     "title": "Client Traffic Out",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
       "legendFormat": "{{instance}} Client Traffic Out"
      }
     ]
    },
    {
     "title": "Peer Traffic In",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(etcd_network_peer_received_bytes_total[5m])) by (instance)",
       "legendFormat": "{{instance}} Peer Traffic In"
      }
     ]
    },
    {
     "title": "Peer Traffic Out",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(etcd_network_peer_sent_bytes_total[5m])) by (instance)",
       "legendFormat": "{{instance}} Peer Traffic Out"
      }
     ]
    }
   ]
  }
 ]
}